parameters:
    base64.service.class: images\base64ConverterBundle\Services\base64Service
services:
     base64_converter:
        class: %base64.service.class%
        arguments: ['@service_container']
